CREATE DATABASE IF NOT EXISTS `${SQL_DATABASE}`;

CREATE USER '${WORDPRESS_DB_USER0}'@'%' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON `${SQL_DATABASE}`.* TO '${WORDPRESS_DB_USER0}'@'%' WITH GRANT OPTION;

CREATE USER '${WORDPRESS_DB_USER1}'@'%' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE ON `${SQL_DATABASE}`.* TO '${WORDPRESS_DB_USER1}'@'%';

FLUSH PRIVILEGES;